<?php

namespace AppBundle\Repository;

/**
 * PlaineModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaineModelRepository extends \Doctrine\ORM\EntityRepository
{
}
